<?php

/**
 * @file
 * Islandora Defaults stuff.
 */

/**
 * Implements hook_rdf_namespaces().
 */
function islandora_defaults_rdf_namespaces() {
  return [
    'relators' => 'http://id.loc.gov/vocabulary/relators/',
    'opaque'	=> 'http://opaquenamespace.org/ns',
    'dbpedia'	=> 'http://dbpedia.org/ontology/',
    'identifiers' => 'https://id.loc.gov/vocabulary/identifiers.html',
    'viaf	' => 'https://viaf.org/viaf',
    'lcnaf' => 'http://id.loc.gov/authorities/names.html',
    'lcsh' => 'http://id.loc.gov/authorities/subjects.html',
    'marcgac' => 'https://id.loc.gov/vocabulary/countries.html',
    'frequency' => 'https://id.loc.gov/vocabulary/frequencies.html',
    'resource' => 'http://id.loc.gov/vocabulary/resourceTypes.html',
    'rdau' => 'http://www.rdaregistry.info/Elements/u/#',
  ];
}
