<?php

/**
 * @file
 * Islandora Defaults stuff.
 */

/**
 * Implements hook_rdf_namespaces().
 */
function islandora_defaults_rdf_namespaces() {
  return [
    'relators' => 'http://id.loc.gov/vocabulary/relators/',
    'opaque'	=> 'http://opaquenamespace.org/ns',
    'dbpedia'	=> 'http://dbpedia.org/ontology/',
    'identifiers' => 'https://id.loc.gov/vocabulary/identifiers.html',
    'viaf	' => 'https://viaf.org/viaf',
    'lcnaf' => 'http://id.loc.gov/authorities/names.html',
    'lcsh' => 'http://id.loc.gov/authorities/subjects.html',
    'marcgac' => 'http://id.loc.gov/search/?q=&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fvocabulary%2Fcountries',
    'frequency' => 'http://id.loc.gov/vocabulary/frequencies/collection_publicationsFrequencies',
    'resource' => 'http://id.loc.gov/vocabulary/resourceTypes.html',
    'premis' => 'http://id.loc.gov/vocabulary/preservation/eventType/collection_PREMIS',
    'rdau' => 'http://www.rdaregistry.info/Elements/u/#',
  ];
}
